Gather data from output side

In [2]:
import pandas as pd

In [3]:
df2 = pd.read_csv('grad_rates.csv')
outputs = list(df2['Campus'])

In [5]:
import sqlite3
con = sqlite3.connect('data.db')
df = pd.read_sql('select * from ratings',con)
inputs = list(df['campus'])

In [6]:
both = [o for o in outputs if o in inputs]
both
len(both)

['Bakersfield',
 'Channel Islands',
 'Chico',
 'Dominguez Hills',
 'East Bay',
 'Fresno',
 'Fullerton',
 'Long Beach',
 'Los Angeles',
 'Monterey Bay',
 'Northridge',
 'Pomona',
 'Sacramento',
 'San Bernardino',
 'San Marcos',
 'Stanislaus']

16

In [9]:
df2.describe

<bound method NDFrame.describe of               Campus   2000   2001   2002   2003   2004   2005   2006   2007  \
0        Bakersfield  0.417  0.397  0.445  0.384  0.430  0.414  0.386  0.395
1    Channel Islands  0.000  0.000  0.000  0.525  0.584  0.539  0.511  0.516
2              Chico  0.537  0.524  0.557  0.580  0.618  0.590  0.572  0.561
3    Dominguez Hills  0.329  0.282  0.340  0.349  0.309  0.244  0.276  0.294
4           East Bay  0.432  0.399  0.444  0.476  0.451  0.433  0.410  0.381
5             Fresno  0.455  0.481  0.480  0.478  0.506  0.494  0.481  0.486
6          Fullerton  0.491  0.499  0.490  0.516  0.514  0.501  0.512  0.535
7           Humboldt  0.442  0.414  0.422  0.415  0.366  0.397  0.405  0.401
8         Long Beach  0.478  0.468  0.554  0.544  0.540  0.540  0.569  0.603
9        Los Angeles  0.348  0.313  0.306  0.337  0.374  0.365  0.365  0.357
10  Maritime Academy  0.531  0.627  0.620  0.687  0.611  0.623  0.579  0.587
11      Monterey Bay  0.356  0.363  0.387  0.415  0.409  0.378  0.368  0.383
12        Northridge  0.400  0.405  0.411  0.437  0.479  0.461  0.480  0.458
13            Pomona  0.483  0.489  0.504  0.529  0.566  0.503  0.508  0.524
14        Sacramento  0.421  0.424  0.416  0.439  0.420  0.416  0.414  0.429
15    San Bernardino  0.443  0.383  0.437  0.455  0.440  0.446  0.435  0.411
16         San Diego  0.583  0.564  0.613  0.663  0.662  0.656  0.660  0.662
17     San Francisco  0.424  0.442  0.437  0.475  0.480  0.465  0.473  0.455
18          San Jose  0.414  0.420  0.414  0.464  0.480  0.464  0.469  0.481
19   San Luis Obispo  0.670  0.661  0.694  0.717  0.729  0.746  0.722  0.697
20        San Marcos  0.381  0.437  0.451  0.473  0.442  0.485  0.446  0.479
21            Sonoma  0.508  0.556  0.496  0.529  0.569  0.567  0.549  0.539
22        Stanislaus  0.501  0.516  0.527  0.495  0.495  0.491  0.487  0.520
23        Systemwide  0.478  0.474  0.489  0.513  0.524  0.513  0.514  0.518

     2008
0   0.412
1   0.615
2   0.593
3   0.323
4   0.381
5   0.524
6   0.557
7   0.438
8   0.652
9   0.411
10  0.542
11  0.453
12  0.468
13  0.564
14  0.437
15  0.480
16  0.660
17  0.497
18  0.516
19  0.750
20  0.485
21  0.555
22  0.533
23  0.540  >

In [11]:
data = df.merge(df2,left_on='campus' ,right_on='Campus')

In [12]:
data.head()

,index,school,url,sid,overall_rating,avg_prof_rating,num_ratings,clubs,facilities,food,...,Campus,2000,2001,2002,2003,2004,2005,2006,2007,2008
0,0,"California State Polytechnic University, Pomona",http://www.ratemyprofessors.com/campusRatings....,14774,3.9,3.66,76,4.1,3.5,3.7,...,Pomona,0.483,0.489,0.504,0.529,0.566,0.503,0.508,0.524,0.564
1,2,California State University - East Bay,http://www.ratemyprofessors.com/campusRatings....,167,3.4,3.77,182,3.4,3.5,3.3,...,East Bay,0.432,0.399,0.444,0.476,0.451,0.433,0.410,0.381,0.381
2,3,"California State University, Northridge",http://www.ratemyprofessors.com/campusRatings....,163,3.8,3.79,517,3.8,3.9,3.8,...,Northridge,0.400,0.405,0.411,0.437,0.479,0.461,0.480,0.458,0.468
3,4,California State University Dominguez Hills,http://www.ratemyprofessors.com/campusRatings....,160,3.8,3.77,202,3.6,3.8,3.6,...,Dominguez Hills,0.329,0.282,0.340,0.349,0.309,0.244,0.276,0.294,0.323
4,5,California State University Long Beach,http://www.ratemyprofessors.com/campusRatings....,162,4.0,3.84,458,4.2,4.4,3.7,...,Long Beach,0.478,0.468,0.554,0.544,0.540,0.540,0.569,0.603,0.652

In [15]:
data.drop(['url','school','index'],axis=1)

,sid,overall_rating,avg_prof_rating,num_ratings,clubs,facilities,food,happiness,internet,location,...,Campus,2000,2001,2002,2003,2004,2005,2006,2007,2008
0,14774,3.9,3.66,76,4.1,3.5,3.7,3.6,4.1,4.2,...,Pomona,0.483,0.489,0.504,0.529,0.566,0.503,0.508,0.524,0.564
1,167,3.4,3.77,182,3.4,3.5,3.3,2.9,3.3,3.6,...,East Bay,0.432,0.399,0.444,0.476,0.451,0.433,0.410,0.381,0.381
2,163,3.8,3.79,517,3.8,3.9,3.8,3.5,3.7,4.3,...,Northridge,0.400,0.405,0.411,0.437,0.479,0.461,0.480,0.458,0.468
3,160,3.8,3.77,202,3.6,3.8,3.6,3.6,3.8,4.1,...,Dominguez Hills,0.329,0.282,0.340,0.349,0.309,0.244,0.276,0.294,0.323
4,162,4.0,3.84,458,4.2,4.4,3.7,3.6,3.9,4.2,...,Long Beach,0.478,0.468,0.554,0.544,0.540,0.540,0.569,0.603,0.652
5,161,3.6,3.83,332,3.5,3.5,3.7,3.3,3.5,4.0,...,Fresno,0.455,0.481,0.480,0.478,0.506,0.494,0.481,0.486,0.524
6,156,3.6,3.81,187,3.6,3.5,3.4,3.3,3.3,3.8,...,Stanislaus,0.501,0.516,0.527,0.495,0.495,0.491,0.487,0.520,0.533
7,158,3.3,3.76,117,3.2,3.5,3.7,3.0,3.2,3.6,...,Bakersfield,0.417,0.397,0.445,0.384,0.430,0.414,0.386,0.395,0.412
8,157,3.3,3.84,348,3.3,3.6,3.4,3.1,3.4,3.5,...,Los Angeles,0.348,0.313,0.306,0.337,0.374,0.365,0.365,0.357,0.411
9,164,3.6,3.76,373,3.4,3.7,3.6,3.4,3.5,3.8,...,Sacramento,0.421,0.424,0.416,0.439,0.420,0.416,0.414,0.429,0.437
10,168,3.6,3.68,132,3.3,3.9,3.5,3.1,3.4,3.9,...,Monterey Bay,0.356,0.363,0.387,0.415,0.409,0.378,0.368,0.383,0.453
11,166,3.8,3.76,447,3.8,4.0,3.6,3.5,3.7,3.9,...,Fullerton,0.491,0.499,0.490,0.516,0.514,0.501,0.512,0.535,0.557
12,165,3.7,3.89,270,3.7,3.6,4.0,3.5,3.8,4.1,...,San Bernardino,0.443,0.383,0.437,0.455,0.440,0.446,0.435,0.411,0.480
13,155,3.7,3.78,236,3.6,3.8,3.9,3.2,3.7,4.2,...,San Marcos,0.381,0.437,0.451,0.473,0.442,0.485,0.446,0.479,0.485
14,4766,3.6,3.66,194,3.5,3.7,3.6,3.5,3.5,4.2,...,Channel Islands,0.000,0.000,0.000,0.525,0.584,0.539,0.511,0.516,0.615
15,159,4.0,3.72,262,3.6,4.2,4.1,3.5,4.1,4.4,...,Chico,0.537,0.524,0.557,0.580,0.618,0.590,0.572,0.561,0.593